services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      PORT: 3000
      UPLOAD_PROVIDER: local
      DATABASE_URL: postgresql://postgres:postgres@db:5432/mission_db?schema=public
      JWT_ACCESS_TOKEN_SECRET: ${JWT_ACCESS_TOKEN_SECRET}
      JWT_REFRESH_TOKEN_SECRET: ${JWT_REFRESH_TOKEN_SECRET}
    depends_on:
      - db
    volumes:
      - uploads:/app/public

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mission_db
    ports:
      - "5434:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  uploads:
  dbdata:
