name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy
        run: |
          cd mission9-10-11
          npm ci
          npm run build
          npm run prisma:migrate:deploy
          pm2 reload panda-market
          echo "Deployment successful!"
