name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    defaults:
      run:
        working-directory: mission9-10-11

    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Migrate
        run: npm run prisma:migrate:deploy

      - name: Restart app
        run: |
          pm2 reload panda-market || pm2 start dist/src/main.js --name panda-market
          pm2 save

      - name: Done
        run: echo "Deployment successful!"
